name: BackToSpawn
main: BackToSpawn/Main
version: 1.0.1
description: Pointless plugin that lets you teleport back to spawn/s
api: [1.12.0]
authors: ["Syntaxious", "XFuryMCPE"]

commands:
 spawn:
  description: Teleport player to spawn
  usage: /spawn <default:here>
  aliases: [s]
  permission: backtospawn.cmd
permissions:
 backtospawn.cmd:
  description: "Allows the user to teleport to spawn"
  default: true
