name: BackToSpawn
main: BackToSpawn/Main
version: 1.0
api: [1.12.0]
author: Syntaxious

load: POSTWORLD
description: teleport player to spawn
commands:
 backtospawn:
  description: Teleport player to spawn
  usage: "/s"
  permission: backtospawn.cmd
permissions:
 backtospawn.cmd:
  description: "Allows the user to teleport to spawn"
  default: true
